### ISSUE TITLE
fatal error: 'windows.h' file not found

### ISSUE THREAD

**Issue by mhulse** [JayrAlencar/node-beep#1]
Got this when installing:

``` bash
$ npm install node-beep --save-dev
  CXX(target) Release/obj.target/beep/beep.o
../beep.cc:4:10: fatal error: 'windows.h' file not found
#include <windows.h>
         ^
1 error generated.
make: *** [Release/obj.target/beep/beep.o] Error 1
```

Node v6.8.1
npm v3.10.8

**Comment by jayralencar** [comment]
Are you using linux?

**Comment by mhulse** [comment]
Oh, sorry, Unix/macOS Sierra.

Let me know if I can help test (or, maybe it' just my machine?)

**Comment by mhulse** [comment]
Also, I have a homebrew-installed version of Node.

**Comment by jayralencar** [comment]
This package works just in Windows.

**Comment by mhulse** [comment]
Ahhhh, my bad. I guess I should have realized that considering the name `windows.h`. 😆 

Thanks!

**Comment by onury** [comment]
@jayralencar you should mention "windows-only" in your readme.

**Comment by jayralencar** [comment]
I am sorry, this package is discontinued.
